name: 12 - Outputs
on:
    workflow_dispatch: 
        inputs:
            build-status:
                type: choice
                options:
                    - success
                    - failure

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{steps.build.outputs.status}}
            output1: ${{steps.build.outputs.output1}}
        steps:
            - name: Build
              id: build
              run: |
               echo "status=${{inputs.build-status}}" >> "$GITHUB_OUTPUT"
               echo "output1=value1" >> "$GITHUB_OUTPUT"
               echo "output2=value2" >> "$GITHUB_OUTPUT"
               cat "$GITHUB_OUTPUT"
               echo "mistake=true" >> "$GITHUB_OUTPUT"
               cat "$GITHUB_OUTPUT"

    deploy:                    
        runs-on: ubuntu-latest
        needs: build
        if: ${{ needs.build.outputs.build-status == 'success' }}
        steps:
            - name: Print Outputs
              id: print-outputs
              run: echo output1 from build job - ${{needs.build.outputs.output1}}
            - name: Deploy
              run: echo "Deploying"
