name: 12 - Outputs
on:
    workflow_dispatch: 
        inputs:
            build-status:
                type: choice
                options:
                    - success
                    - failure

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{steps.build-step.outputs.status}}
        steps:
            - name: Build
              id: build-step
              run: echo "status=${{inputs.build-status}}" >> "$GITHUB_OUTPUT"
    deploy:                    
        runs-on: ubuntu-latest
        needs: build
        if: ${{ needs.build.outputs.build-status == 'success' }}
        steps:
            - name: Deploy
              run: echo "Deploying"
